### PR TITLE
Update feature template

### PR DESCRIPTION
**Pull request by KPeen**
Updated the feature template with the information from ADO.

### CODE REVIEW

**Review by MadsBloendAndersen — APPROVED** [review]
Hej Katja. Det ser rigtig fint ud.

**Review by PerLysemose — APPROVED** [review]

**Comment by PerLysemose** [comment]
Jep, det er ser fint ud :-)

**Review by kariws — APPROVED** [review]
should we keep the wording "epic" or differentiate between epicand feature? Meaning 2 templates?

**Review by KPeen — COMMENTED** [review]
Ok

**Pull request merged**
